### ISSUE TITLE
Users - Back end theme - Unknown option: default

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao-demo#20] opened 2024-01-27 13:00 UTC
Back end users have a wrong Back end theme:
![Users-BE-Theme-wrong](https://github.com/contao/contao-demo/assets/1218809/d3d20d7f-1de5-4c5d-8b76-1aea6440e11b)

"flexible" should be set here.

Contao 5.2.8 with Demo, newly installed.

**Comment by zoglo** [comment] 2024-01-27 13:01
Duplicate of #17

**Closed as completed** 2024-01-27 13:04 UTC
